// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cart struct {
	Contents []*Content `json:"contents"`
}

type Content struct {
	Sku      string `json:"sku"`
	Name     string `json:"name"`
	Quantity int    `json:"quantity"`
}

type NewProduct struct {
	Sku      string  `json:"sku"`
	Name     string  `json:"name"`
	Price    float64 `json:"price"`
	Quantity int     `json:"quantity"`
}

type NewPromo struct {
	Sku           string  `json:"sku"`
	Scheme        string  `json:"scheme"`
	Freebiesku    *string `json:"freebiesku"`
	Minqty        *int    `json:"minqty"`
	Payonly       *int    `json:"payonly"`
	Percentageoff *int    `json:"percentageoff"`
}

type Product struct {
	ID       string  `json:"ID"`
	Sku      string  `json:"sku"`
	Name     string  `json:"name"`
	Price    float64 `json:"price"`
	Quantity int     `json:"quantity"`
}

type Promo struct {
	ID            string `json:"ID"`
	Sku           string `json:"sku"`
	Scheme        string `json:"scheme"`
	Freebiesku    string `json:"freebiesku"`
	Minqty        int    `json:"minqty"`
	Payonly       int    `json:"payonly"`
	Percentageoff int    `json:"percentageoff"`
}

type Response struct {
	Total float64 `json:"total"`
}

type ResponseCreated struct {
	ID string `json:"ID"`
}
